# In _config.yml
title: Image Analyis with Napari and Python (HIP 2022)

author: Robert Haase and Marcelo Zoccoler
logo: biapol_logo.png
execute:
  execute_notebooks: off

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/BiAPoL/HIP_Introduction_to_Napari_and_image_processing_with_Python_2022
html:
  use_repository_button: true